Trigger workflows with secrets using PR comments

diff --git a/.github/actions/setup/action.yml b/.github/actions/setup/action.yml
--- a/.github/actions/setup/action.yml
+++ b/.github/actions/setup/action.yml
@@ -1,5 +1,5 @@
 name: setup
-description: "Setup Java"
+description: "Verify checked out commits and setup Java"
 inputs:
   java-version:
     description: "Java version to setup"
@@ -11,6 +11,22 @@ inputs:
 runs:
   using: composite
   steps:
+      - name: Verify args
+        shell: bash
+        if: github.event_name == 'repository_dispatch' && github.event.client_payload.slash_command.args.named.sha == ''
+        run: |
+          echo >&2 "Dispatched from a slash command but missing the 'sha' argument"
+          exit 1
+      - name: Verify commit
+        shell: bash
+        run: |
+          expected=${{ github.event_name == 'repository_dispatch' &&
+                github.event.client_payload.pull_request.head.sha || '' }}
+          actual=$(git log -1 --format='%H')
+          if [ -n "$expected" ] && [ "$actual" != "$expected" ]; then
+            echo >&2 "Expected to checkout $expected but got $actual"
+            exit 1
+          fi
       - name: Fetch base ref to find merge-base for GIB
         shell: bash
         run: .github/bin/git-fetch-base-ref.sh
